<a href="https://colab.research.google.com/github/KhushiShah05/AI-Engineer-Learning-Journey/blob/main/Numpy/Day-1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numerical python
this liabrary used for :
-Araays
-Mathematics
-Statistics
-Matrix Operation
-Data science
-ML
python list is good for small tasks
but for large calculations you need numpy


In [4]:
import numpy as np
arr = np.array([10,20,30,40])
print(arr)
print(arr[1])

[10 20 30 40]
20


Challenge-1

In [5]:
arr = ([5,10,15,20,25])
print(arr)

[5, 10, 15, 20, 25]


Challenge-2


In [6]:
arr = ([100,200,300,400])
print(arr[1])

200


Challenge-3

In [11]:
arr =np.array([1,2,3,4,5])
res = arr + 5
print(res)


[ 6  7  8  9 10]


challenge-4

In [12]:
arr = np.array([2,4,6,8])
res = arr * 3
print(res)

[ 6 12 18 24]
